frr defaults traditional
hostname isp-pe
agentx
log stdout
!
ip route 203.0.113.0/24 Null0
!
router bgp 64500
 bgp router-id 200.200.10.1
 no bgp ebgp-requires-policy
 neighbor 200.200.10.2 remote-as 65001
 neighbor 200.200.10.2 description CLIENTE-EDGE-MK1
 address-family ipv4 unicast
  network 203.0.113.0/24
 exit-address-family
!
